TechJobsPersistent/Models/Employer.cs
using System;
namespace TechJobsPersistent.Models
{
    public class Employer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }

        public Employer()
        {
        }

        public Employer(string name, string location)
        {
            Name = name;
            Location = location;
        }
    }
}

TechJobsPersistent/Controllers/EmployerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TechJobsPersistent.Data;
using TechJobsPersistent.Models;
using TechJobsPersistent.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TechJobsPersistent.Controllers
{
    public class EmployerController : Controller
    {

        private JobDbContext _context { get; set; }

        public EmployerController(JobDbContext dbContext)
        {
            this._context = dbContext;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            List<Employer> employers = _context.Employers.ToList();
            return View(employers);
        }

        public IActionResult Add()
        {
            AddEmployerViewModel addEmployerViewModel = new AddEmployerViewModel();
            return View(addEmployerViewModel);
        }

        public IActionResult ProcessAddEmployerForm(AddEmployerViewModel addEmployerViewModel)
        {
            if (ModelState.IsValid)
            {
                Employer newEmployer = new Employer()
                {
                    Name = addEmployerViewModel.Name,
                    Location = addEmployerViewModel.Location
                };

                _context.Employers.Add(newEmployer);
                _context.SaveChanges();

                return Redirect("/Employer");
            }

            return View(addEmployerViewModel);
        }

        public IActionResult About(int id)
        {
            Employer employer = _context.Employers.Find(id);
            return View(employer);
        }
    }
}

TechJobsPersistent/Views/Employer/About.cshtml
@model TechJobsPersistent.Models.Employer

<h1>Employer: @Model.Name</h1>

<div>
    <p>Name: @Model.Name</p>
    <p>Location: @Model.Location</p>
</div>

TechJobsPersistent/Views/Employer/Add.cshtml
@model TechJobsPersistent.ViewModels.AddEmployerViewModel

<h1>Add New Employer</h1>

<form asp-controller="Employer" asp-action="ProcessAddEmployerForm" method="post">
    <div class="form-group">
        <label asp-for="Name">Employer Name</label>
        <input asp-for="Name"/>
    </div>

    <div class="form-group">
        <label asp-for="Location">Employer Location</label>
        <input asp-for="Location" />
    </div>

    <input type="submit" value="Submit" />
</form>

TechJobsPersistent/Views/Employer/Index.cshtml
@model List<TechJobsPersistent.Models.Employer>

<h1>Employers Currently Hiring</h1>

@if (Model.Count == 0)
{
    <p>No employers are currently hiring!</p>
}
else
{
    <div>
        <ul>
            @foreach (Employer employer in Model)
            {
                <li>
                    <a asp-controller="Employer" asp-action="About" asp-route-id="@employer.Id">@employer.Name</a>
                </li>
            }
        </ul>
    </div>
}