TechJobsPersistent/Models/Job.cs
using System;
using System.Collections.Generic;

namespace TechJobsPersistent.Models
{
    public class Job
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public Employer Employer { get; set; }

        public int EmployerId { get; set; }

        public List<JobSkill> JobSkills { get; set; }

        public Job()
        {
        }

        public Job(string name)
        {
            Name = name;
        }
    }
}

TechJobsPersistent/Controllers/ListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TechJobsPersistent.Models;
using TechJobsPersistent.Data;
using Microsoft.EntityFrameworkCore;
using TechJobsPersistent.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TechJobsPersistent.Controllers
{
    public class ListController : Controller
    {
        internal static Dictionary<string, string> ColumnChoices = new Dictionary<string, string>()
        {
            {"all", "All"},
            {"employer", "Employer"},
            {"skill", "Skill"}
        };

        internal static List<string> TableChoices = new List<string>()
        {
            "employer",
            "skill"
        };

        private JobDbContext context;

        public ListController(JobDbContext dbContext)
        {
            context = dbContext;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            ViewBag.columns = ColumnChoices;
            ViewBag.tablechoices = TableChoices;
            ViewBag.employers = context.Employers.ToList();
            ViewBag.skills = context.Skills.ToList();
            return View();
        }

        // list jobs by column and value
        public IActionResult Jobs(string column, string value)
        {
            List<Job> jobs = new List<Job>();
            List<JobDetailViewModel> displayJobs = new List<JobDetailViewModel>();

            if (column.ToLower().Equals("all"))
            {
                jobs = context.Jobs
                    .Include(j => j.Employer)
                    .ToList();

                foreach (var job in jobs)
                {
                    List<JobSkill> jobSkills = context.JobSkills
                        .Where(js => js.JobId == job.Id)
                        .Include(js => js.Skill)
                        .ToList();

                    JobDetailViewModel newDisplayJob = new JobDetailViewModel(job, jobSkills);
                    displayJobs.Add(newDisplayJob);
                }

                ViewBag.title = "All Jobs";
            }
            else
            {
                if (column == "employer")
                {
                    jobs = context.Jobs
                        .Include(j => j.Employer)
                        .Where(j => j.Employer.Name == value)
                        .ToList();

                    foreach (Job job in jobs)
                    {
                        List<JobSkill> jobSkills = context.JobSkills
                        .Where(js => js.JobId == job.Id)
                        .Include(js => js.Skill)
                        .ToList();

                        JobDetailViewModel newDisplayJob = new JobDetailViewModel(job, jobSkills);
                        displayJobs.Add(newDisplayJob);
                    }
                }
                else if (column == "skill")
                {
                    List<JobSkill> jobSkills = context.JobSkills
                        .Where(j => j.Skill.Name == value)
                        .Include(j => j.Job)
                        .ToList();

                    foreach (var job in jobSkills)
                    {
                        Job foundJob = context.Jobs
                            .Include(j => j.Employer)
                            .Single(j => j.Id == job.JobId);

                        List<JobSkill> displaySkills = context.JobSkills
                            .Where(js => js.JobId == foundJob.Id)
                            .Include(js => js.Skill)
                            .ToList();

                        JobDetailViewModel newDisplayJob = new JobDetailViewModel(foundJob, displaySkills);
                        displayJobs.Add(newDisplayJob);
                    }
                }
                ViewBag.title = "Jobs with " + ColumnChoices[column] + ": " + value;
            }
            ViewBag.jobs = displayJobs;

            return View();
        }
    }
}

TechJobsPersistent/Views/List/Index.cshtml
<div class="container body-content">
    <h1>@ViewBag.title</h1>
    <h2 class="centered">View Jobs By Category</h2>
</div>

<table class="centeredTable">
    <tr>
        @foreach (var column in ViewBag.columns)
        {
            @if (column.Key != "all")
            {
                <th>@column.Value</th>
            }
        }
    </tr>
    <tr>
        @foreach (var category in ViewBag.tableChoices)
        {
            <td>
                <ul>
                    @if (category == "employer")
                    {
                        @foreach (var item in ViewBag.employers)
                        {
                            <li>
                                <a asp-controller="List" asp-action="Jobs" asp-route-column="@category" asp-route-value="@item.Name">@item.Name</a>
                            </li>
                        }
                    }
                    else
                    {
                        @foreach (var item in ViewBag.skills)
                        {
                            <li>
                                <a asp-controller="List" asp-action="Jobs" asp-route-column="@category" asp-route-value="@item.Name">@item.Name</a>
                            </li>
                        }
                    }

                </ul>
            </td>
        }
    </tr>
</table>

TechJobsPersistent/Views/List/Jobs.cshtml
<div class="container body-content">

    <h1>@ViewBag.title</h1>

    <table>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Employer</th>
            <th>Skills</th>
        </tr>
        @foreach (var job in ViewBag.jobs)
        {
            <tr>
                <td>@job.JobId</td>
                <td>@job.Name</td>
                <td>@job.EmployerName</td>
                <td>@job.SkillText</td>
            </tr>
        }
    </table>

</div>