TechJobsPersistent/Models/Skill.cs
using System;
namespace TechJobsPersistent.Models
{
    public class Skill
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        public Skill()
        {
        }

        public Skill(string name, string description)
        {
            Name = name;
            Description = description;
        }
    }
}

TechJobsPersistent/ViewModels/AddJobViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;
using TechJobsPersistent.Models;

namespace TechJobsPersistent.ViewModels
{
    public class AddJobViewModel
    {
        [Required(ErrorMessage = "A Name is required")]
        public string Name { get; set; }

        public int EmployerId { get; set; }

        public List<SelectListItem> Employers { get; set; } // null

        public List<Skill> Skills { get; set; } // null

        public AddJobViewModel()
        {
        }

        public AddJobViewModel(List<Employer> employers, List<Skill> skills)
        {
            this.Skills = skills;

            // This is the fix:
            this.createSelectListItems(employers);

            // This is the pre-existing answer
            // this.Employers = new List<SelectListItem>();

            // foreach (Employer employer in employers)
            // {
            //     this.Employers.Add(
            //         new SelectListItem
            //         {
            //             Value = employer.Id.ToString(),
            //             Text = employer.Name
            //         });
            // }

        }

        public void createSelectListItems(List<Employer> employers)
        {
            this.Employers = new List<SelectListItem>();

            foreach (Employer employer in employers)
            {
                this.Employers.Add(
                    new SelectListItem
                    {
                        Value = employer.Id.ToString(),
                        Text = employer.Name
                    });
            }
        }
    }
}

TechJobsPersistent/Controllers/SkillController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TechJobsPersistent.Data;
using TechJobsPersistent.Models;
using TechJobsPersistent.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TechJobsPersistent.Controllers
{
    public class SkillController : Controller
    {
        private JobDbContext context;

        public SkillController(JobDbContext dbContext)
        {
            context = dbContext;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            List<Skill> skills = context.Skills.ToList();
            return View(skills);
        }

        public IActionResult Add()
        {
            Skill skill = new Skill();
            return View(skill);
        }

        [HttpPost]
        public IActionResult Add(Skill skill)
        {
            if (ModelState.IsValid)
            {
                context.Skills.Add(skill);
                context.SaveChanges();
                return Redirect("/Skill/");
            }

            return View("Add", skill);
        }

        public IActionResult AddJob(int id)
        {
            Job theJob = context.Jobs.Find(id);
            List<Skill> possibleSkills = context.Skills.ToList();
            AddJobSkillViewModel viewModel = new AddJobSkillViewModel(theJob, possibleSkills);
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult AddJob(AddJobSkillViewModel viewModel)
        {
            if (ModelState.IsValid)
            {

                int jobId = viewModel.JobId;
                int skillId = viewModel.SkillId;

                List<JobSkill> existingItems = context.JobSkills
                    .Where(js => js.JobId == jobId)
                    .Where(js => js.SkillId == skillId)
                    .ToList();

                if (existingItems.Count == 0)
                {
                    JobSkill jobSkill = new JobSkill
                    {
                        JobId = jobId,
                        SkillId = skillId
                    };
                    context.JobSkills.Add(jobSkill);
                    context.SaveChanges();
                }

                return Redirect("/Home/Detail/" + jobId);
            }

            return View(viewModel);
        }

        public IActionResult About(int id)
        {
            List<JobSkill> jobSkills = context.JobSkills
                .Where(js => js.SkillId == id)
                .Include(js => js.Job)
                .Include(js => js.Skill)
                .ToList();

            return View(jobSkills);
        }

    }
}

TechJobsPersistent/Views/Skill/About.cshtml
@model List<TechJobsPersistent.Models.JobSkill>

@if (Model.Count == 0)
{
    <h1>No jobs with the given skill!</h1>
}
else
{
    <h1>Jobs with the Skill: @Model[0].Skill.Name</h1>
    <p>Skill Description: @Model[0].Skill.Description</p>

    <ul>
        @foreach (var jobSkill in Model)
        {
            <li>@jobSkill.Job.Name</li>
        }
    </ul>

}

TechJobsPersistent/Views/Skill/Add.cshtml
@model TechJobsPersistent.Models.Skill

<h1>Add New Skill</h1>

<form asp-controller="Skill" asp-action="Add" method="post">
    <div class="form-group">
        <label asp-for="Name">Skill Name</label>
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description">Skill Description</label>
        <input asp-for="Description" />
        <span asp-validation-for="Description"></span>
    </div>
    <input type="submit" value="Submit" />
</form>

TechJobsPersistent/Views/Skill/AddJob.cshtml
@model TechJobsPersistent.ViewModels.AddJobSkillViewModel

<h1>Add Tag to Event: @Model.Job.Name</h1>

<form asp-controller="Skill" asp-action="AddJob" method="post">
    <input type="hidden" value="@Model.Job.Id" name="JobId" />
    <div class="form-group">
        <label asp-for="SkillId">Skill</label>
        <select asp-for="SkillId" asp-items="Model.Skills"></select>
        <span asp-validation-for="SkillId"></span>
    </div>
    <input type="submit" value="Add Skill" />
</form>

TechJobsPersistent/Views/Skill/Index.cshtml
@model List<TechJobsPersistent.Models.Skill>

<h1>In-demand Skills</h1>

<p><a asp-controller="Skill" asp-action="Add">Add a Skill</a></p>

@if (Model.Count == 0)
{
    <p>No skills are currently listed!</p>
}
else
{
    <div>
        <ul>
            @foreach (Skill skill in Model)
            {
                <li>
                    <a asp-controller="Skill" asp-action="About" asp-route-id="@skill.Id">@skill.Name</a>
                </li>
            }
        </ul>
    </div>
}